version: "3.7"

services:
  db:
    container_name: wordpress_boilerplate_mysql
    image: mysql:latest
    volumes:
      - ./db-store:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    restart: always
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress_boilerplate_wordpress
    image: wordpress:latest
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/
    working_dir: /var/www/html/
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASS}

  phpmyadmin:
    container_name: wordpress_boilerplate_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    depends_on:
      - db
volumes:
  src:
  db-store:
